language: node_js
os:
  - linux
dist: xenial
node_js:
  - node
  - 14
  - 12
  - 10
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run lint
      deploy:
        - provider: script
          script: npx semantic-release
